
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Button BtnEntrar;
	private global::Gtk.Label label2;
	private global::Gtk.Label label3;
	private global::Gtk.Entry txtLogin;
	private global::Gtk.Entry txtPassword;
	private global::Gtk.Label label1;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.BtnEntrar = new global::Gtk.Button ();
		this.BtnEntrar.CanFocus = true;
		this.BtnEntrar.Name = "BtnEntrar";
		this.BtnEntrar.UseUnderline = true;
		this.BtnEntrar.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.fixed1.Add (this.BtnEntrar);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.BtnEntrar]));
		w1.X = 136;
		w1.Y = 184;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("label2");
		this.fixed1.Add (this.label2);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
		w2.X = 55;
		w2.Y = 116;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("label3");
		this.fixed1.Add (this.label3);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label3]));
		w3.X = 157;
		w3.Y = 15;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtLogin = new global::Gtk.Entry ();
		this.txtLogin.CanFocus = true;
		this.txtLogin.Name = "txtLogin";
		this.txtLogin.IsEditable = true;
		this.txtLogin.InvisibleChar = '•';
		this.fixed1.Add (this.txtLogin);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txtLogin]));
		w4.X = 127;
		w4.Y = 69;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtPassword = new global::Gtk.Entry ();
		this.txtPassword.CanFocus = true;
		this.txtPassword.Name = "txtPassword";
		this.txtPassword.IsEditable = true;
		this.txtPassword.InvisibleChar = '•';
		this.fixed1.Add (this.txtPassword);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txtPassword]));
		w5.X = 126;
		w5.Y = 111;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
		this.fixed1.Add (this.label1);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
		w6.X = 60;
		w6.Y = 71;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.BtnEntrar.Clicked += new global::System.EventHandler (this.OnBtnEntrarClicked);
	}
}
